### ISSUE TITLE
change type addIcon & subtractIcon to widget type

### ISSUE THREAD

**Issue by YouSour** [danvick/flutter_touch_spin#11]
hi ,i really this package  , but i think if subtractIcon & addIcon change from **Icon type** to **widget type** i think it better and more customize , what do you think ? 🤔 

#Example
![spinner_input](https://user-images.githubusercontent.com/9318106/111336783-1d5a0a80-86a8-11eb-92c5-56f804c3ac0a.png)

**Comment by awhitford** [comment]
The interface requires Icons because ultimately the increment and decrement widgets are Icon Buttons.  I think it makes more sense for folks to simply specify an icon rather than a whole Icon Button.

If you want more flexibility, then you should consider subclassing.  In order to preserve backwards compatibility, rather than changing TouchSpin, it likely makes more sense to create an alternate subclass.

**Comment by YouSour** [comment]
@awhitford ok , thank you 😄
